"""empty message

Revision ID: da22d52614
Revises: None
Create Date: 2017-10-09 13:37:30.597886

"""

# revision identifiers, used by Alembic.
revision = 'da22d52614'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geotag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.Column('date_modified', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.Column('caption', sa.Text(), nullable=True, index=True),
    sa.Column('filename', sa.String(length=200), nullable=False, unique=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geotag')
    ### end Alembic commands ###
